name: ragline
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - cffi=1.16.0
  - filelock=3.13.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openssl=3.0.12
  - pip=23.3.1
  - pycparser=2.21
  - python=3.11.7
  - pytorch=2.1.0
  - pytorch-cpu=2.1.0
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==4.2.0
      - attrs==23.2.0
      - authlib==1.3.0
      - beautifulsoup4==4.12.3
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cryptography==41.0.7
      - dataclasses-json==0.6.3
      - deprecated==1.2.14
      - distro==1.9.0
      - fastapi==0.109.0
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - huggingface-hub==0.20.2
      - idna==3.6
      - joblib==1.3.2
      - llama-index==0.9.33
      - marshmallow==3.20.2
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - nest-asyncio==1.5.9
      - networkx==3.2.1
      - nltk==3.8.1
      - openai==1.8.0
      - packaging==23.2
      - pandas==2.1.4
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-multipart==0.0.6
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.31.0
      - safetensors==0.4.1
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - sqlalchemy==2.0.25
      - starlette==0.35.1
      - tenacity==8.2.3
      - tiktoken==0.5.2
      - tokenizers==0.15.0
      - tqdm==4.66.1
      - transformers==4.36.2
      - typing-inspect==0.9.0
      - tzdata==2023.4
      - urllib3==2.1.0
      - uvicorn==0.26.0
      - validators==0.22.0
      - watchdog==3.0.0
      - weaviate-client==3.26.1
      - wrapt==1.16.0
      - yarl==1.9.4
